spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/yugabyte
    username: yugabyte # Add your actual database password
    driver-class-name: org.postgresql.Driver
    jpa:
      generate-ddl: false
      properties:
        hibernate:
          default_schema: homeBuddy1
---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/yugabyte
    username: yugabyte
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
